version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symfony/console
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/translation
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/yaml
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/dotenv
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/intl
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/flex
    versions:
    - 1.11.0
    - 1.12.1
  - dependency-name: symfony/notifier
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/asset
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/security-bundle
    versions:
    - 5.1.10
